# Generated by Django 5.2.4 on 2025-07-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_job_deadline_job_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='vacancy',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
