# Generated by Django 5.2.4 on 2025-07-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_job_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='vacancy',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
