# Generated by Django 5.2.4 on 2025-07-28 05:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_job_is_deleted_alter_job_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='about_job',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_requirement',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
