# Generated by Django 5.2.4 on 2025-07-30 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_job_about_job_alter_job_job_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='portal.job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='exp_level',
            field=models.CharField(choices=[('entry-level', 'Entry Level'), ('mid-level', 'Mid Level'), ('senior-level', 'Senior Level'), ('intern', 'Intern')], max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], max_length=20),
        ),
    ]
