# Generated by Django 5.2.4 on 2025-07-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_application_experience_alter_application_job_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewschedule',
            old_name='schedule',
            new_name='schedule_date',
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='interview_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='interview_model',
            field=models.CharField(choices=[('on-site', 'On Site'), ('online', 'Online')], default='on-site', max_length=30),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='schedule_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
