# Generated by Django 5.2.4 on 2025-07-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_rename_schedule_interviewschedule_schedule_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
