# Generated by Django 5.2.4 on 2025-07-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_application_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewschedule',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
