# Generated by Django 5.2.4 on 2025-07-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_interviewschedule_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menulist',
            name='is_main_menu',
        ),
        migrations.RemoveField(
            model_name='menulist',
            name='is_sub_child_menu',
        ),
        migrations.RemoveField(
            model_name='menulist',
            name='is_sub_menu',
        ),
        migrations.RemoveField(
            model_name='menulist',
            name='parent_id',
        ),
    ]
