# Generated by Django 5.2.4 on 2025-07-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_remove_menulist_is_main_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulist',
            name='is_main_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menulist',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
