# Generated by Django 5.2.4 on 2025-08-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_application_status_alter_job_salary_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, null=True),
        ),
    ]
