# Generated by Django 5.2.4 on 2025-08-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
